# Generated by Django 4.0 on 2021-12-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('movies', '0002_movie_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='author',
            field=models.ForeignKey(default='abdallah-alabed', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
